# Generated by Django 3.0.1 on 2020-01-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateways',
            name='gatewayLatitude',
            field=models.FloatField(max_length=50, null=True, verbose_name='Gateway Latitude'),
        ),
        migrations.AlterField(
            model_name='gateways',
            name='gatewayLongitude',
            field=models.FloatField(max_length=50, null=True, verbose_name='Gateway Longitude'),
        ),
    ]
