# Generated by Django 3.0.1 on 2020-01-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20200103_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateways',
            name='gatewayCreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
    ]
