# Generated by Django 3.0.1 on 2020-01-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20200103_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateways',
            name='typeofGateway',
            field=models.CharField(default='Indoor', max_length=50, verbose_name='Type of Gateway'),
        ),
    ]
