# Generated by Django 3.0.2 on 2020-01-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndnodeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationID', models.TextField(verbose_name='App ID')),
                ('description', models.TextField()),
                ('devEUI', models.TextField()),
                ('deviceProfileID', models.TextField()),
                ('name', models.TextField()),
                ('referanceAltitude', models.IntegerField(default=0)),
                ('skipFCntCheck', models.BooleanField(default=True)),
            ],
        ),
    ]
