# Generated by Django 3.0.1 on 2019-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endnode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('rssi', models.CharField(max_length=50)),
                ('snr', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('eui', models.CharField(max_length=50, verbose_name='Device EUI')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
