# Generated by Django 3.0.1 on 2020-01-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endnode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endnode',
            old_name='eui',
            new_name='dev_eui',
        ),
    ]
