# Generated by Django 3.0.1 on 2020-01-03 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endnode', '0002_auto_20200102_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='endnode',
            name='activation_method',
            field=models.CharField(choices=[(0, 'ABP'), (1, 'OTAA')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='endnode',
            name='app_eui',
            field=models.CharField(default='0', max_length=50, verbose_name='Application EUI'),
        ),
        migrations.AddField(
            model_name='endnode',
            name='app_sess_key',
            field=models.CharField(default='0', max_length=50, verbose_name='Application Session Key'),
        ),
        migrations.AddField(
            model_name='endnode',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endnode',
            name='dev_add',
            field=models.CharField(max_length=50, null=True, verbose_name='Device Address'),
        ),
        migrations.AddField(
            model_name='endnode',
            name='device_type',
            field=models.CharField(choices=[(0, 'Temperature-Humidity'), (1, 'Electrical Meter'), (2, 'Water Meter')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='endnode',
            name='net_sess_key',
            field=models.CharField(default='0', max_length=50, verbose_name='Network Session Key'),
        ),
        migrations.AlterField(
            model_name='endnode',
            name='dev_eui',
            field=models.CharField(default='0', max_length=50, verbose_name='Device EUI'),
        ),
    ]
