# Generated by Django 3.0.2 on 2020-01-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endnode', '0002_auto_20200122_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEndnode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationID', models.TextField(verbose_name='App ID')),
                ('description', models.TextField()),
                ('devEUI', models.TextField()),
                ('deviceProfileID', models.TextField()),
                ('name', models.TextField()),
                ('referanceAltitude', models.IntegerField(default=0)),
                ('skipFCntCheck', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EndnodeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceEUI', models.TextField()),
                ('name', models.TextField()),
                ('applicationID', models.TextField()),
                ('description', models.TextField()),
                ('deviceProfilID', models.TextField()),
                ('lastSeenAt', models.TextField(default='Never')),
                ('location', models.TextField(default='Unknown')),
            ],
        ),
    ]
