# Generated by Django 3.0.1 on 2020-01-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_auto_20200103_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateways',
            name='gatewayStatus',
            field=models.CharField(max_length=50, null=True, verbose_name='Gateway Status'),
        ),
    ]
