# Generated by Django 3.0.1 on 2020-01-15 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gateway', '0007_auto_20200114_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayInternalInformations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayEui', models.CharField(max_length=50, null=True, verbose_name='Gateway EUI')),
                ('typeofGateway', models.CharField(default='Indoor', max_length=50, null=True, verbose_name='Type of Gateway')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
