# Generated by Django 3.0.1 on 2020-01-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0008_gatewayinternalinformations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatewayinternalinformations',
            old_name='typeofGateway',
            new_name='typeofGatewayInternal',
        ),
    ]
