# Generated by Django 3.0.2 on 2020-01-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0002_auto_20200110_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addgateway',
            name='gatewayEui',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='addgateway',
            name='gatewayName',
            field=models.TextField(null=True),
        ),
    ]
