# Generated by Django 3.0.1 on 2020-01-03 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatewayCreatedDate', models.DateTimeField(auto_created=True, verbose_name='Created Date')),
                ('gatewayName', models.CharField(max_length=50, verbose_name='Gateway Name')),
                ('gatewayEui', models.CharField(max_length=50, verbose_name='Gateway EUI')),
                ('gatewayDescription', models.CharField(max_length=100, verbose_name='Gateway Description')),
                ('typeofGateway', models.CharField(choices=[('0', 'Indoor'), ('1', 'Outdoor')], default='0', max_length=50, verbose_name='Type of Gateway')),
                ('gatewayLatitude', models.FloatField(max_length=50, verbose_name='Gateway Latitude')),
                ('gatewayLongitude', models.FloatField(max_length=50, verbose_name='Gateway Longitude')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
