# Generated by Django 3.0.2 on 2020-01-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endnode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endnode',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='endnode',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='endnode',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='endnode',
            name='rssiData',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RSSI Data'),
        ),
        migrations.AlterField(
            model_name='endnode',
            name='snrData',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SNR Data'),
        ),
    ]
