# Generated by Django 3.0.2 on 2020-01-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoraAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endnode',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
