# Generated by Django 3.0.1 on 2020-01-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endnode', '0003_auto_20200103_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endnode',
            name='activation_method',
            field=models.CharField(choices=[(0, 'ABP'), (1, 'OTAA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='endnode',
            name='app_eui',
            field=models.CharField(max_length=50, null=True, verbose_name='Application EUI'),
        ),
        migrations.AlterField(
            model_name='endnode',
            name='app_sess_key',
            field=models.CharField(max_length=50, null=True, verbose_name='Application Session Key'),
        ),
        migrations.AlterField(
            model_name='endnode',
            name='dev_eui',
            field=models.CharField(max_length=50, null=True, verbose_name='Device EUI'),
        ),
        migrations.AlterField(
            model_name='endnode',
            name='net_sess_key',
            field=models.CharField(max_length=50, null=True, verbose_name='Network Session Key'),
        ),
    ]
