# Generated by Django 3.0.1 on 2020-01-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endnode', '0004_auto_20200103_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endnode',
            name='device_type',
            field=models.CharField(choices=[(0, 'Temperature-Humidity'), (1, 'Electrical Meter'), (2, 'Water Meter')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='endnode',
            name='rssi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='endnode',
            name='snr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
